---
- name: Install monitoring and forwarding tools
  hosts: monitoring
  become: true
  tasks:
    - name: Install logrotate
      apt:
        name: logrotate
        state: present

    - name: Configure logrotate to create test log file
      lineinfile:
        path: /etc/logrotate.conf
        regexp: '^\/var\/log\/test\.log'
        line: '/var/log/test.log { create 0644 root root }'
        state: present

    - name: Create test log file
      copy:
        content: 'This is a test log message    \n'
        dest: /var/log/test.log
        mode: '0644'

    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present

    - name: Configure rsyslog to forward logs to another Ubuntu system
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^.*\*\.\*'
        line: '. @@{{ destination_ip }}'
        state: present
      vars:
        destination_ip: 192.168.56.129

    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
